#!/usr/bin/env python3
"""Generate master-first router navigation from local routing metadata."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping


SKILLS_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROUTING = SKILLS_ROOT / "config" / "routing.json"
DEFAULT_OUTPUT = SKILLS_ROOT / "INDEX.md"


def load_routing(path: Path) -> dict[str, Any]:
    """Load the minimal routing fields needed to generate navigation."""

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise ValueError(f"cannot read routing config: {error}") from error
    except json.JSONDecodeError as error:
        raise ValueError(f"invalid routing JSON: {error}") from error
    if not isinstance(data, dict):
        raise ValueError("routing config must contain a JSON object")
    routes = data.get("routes")
    if not isinstance(routes, list) or not all(isinstance(route, dict) for route in routes):
        raise ValueError("routing config must contain a routes list")
    return data


def _table_cell(value: Any) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def render_index(routing: Mapping[str, Any]) -> str:
    """Render a compact deterministic master-first navigation document."""

    routes = routing.get("routes")
    if not isinstance(routes, list):
        raise ValueError("routing config must contain a routes list")
    suite = routing.get("suite") if isinstance(routing.get("suite"), Mapping) else {}
    master = routing.get("master_skill") if isinstance(routing.get("master_skill"), Mapping) else {}
    title = _table_cell(suite.get("title") if isinstance(suite, Mapping) else "") or "Intelligent Reverse Task Router"
    master_title = _table_cell(master.get("title") if isinstance(master, Mapping) else "") or "Master skill"
    master_path = _table_cell(master.get("path") if isinstance(master, Mapping) else "") or "SKILL.md"
    lines = [
        "<!-- Generated by scripts/refresh-skill-index.py. Do not edit by hand. -->",
        "",
        f"# {title}",
        "",
        f"Start with [{master_title}]({master_path}), then follow the selected workflow and its indexed subskills/tools.",
        "",
        "| Workflow | Phase | Risk | Authorization | Indexed tools |",
        "| --- | --- | --- | --- | --- |",
    ]
    for route in routes:
        if not isinstance(route, Mapping):
            raise ValueError("routing config must contain object-shaped routes")
        skill_id = _table_cell(route.get("skill_id"))
        workflow_title = _table_cell(route.get("title"))
        phase = _table_cell(route.get("phase"))
        risk_level = _table_cell(route.get("risk_level")) or "standard"
        authorization = "required" if route.get("requires_authorization") else "not required"
        tools = _table_cell(", ".join(str(tool) for tool in route.get("tools", []) if str(tool))) or "-"
        lines.append(
            f"| [{workflow_title}]({skill_id}/SKILL.md) | {phase} | {risk_level} | {authorization} | {tools} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate local intelligent reverse-router navigation; no targets are read or executed."
    )
    parser.add_argument(
        "--routing",
        type=Path,
        default=DEFAULT_ROUTING,
        help="Local routing JSON path (default: %(default)s).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Generated index path (default: %(default)s).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Fail when the index is missing or stale.")
    mode.add_argument("--stdout", action="store_true", help="Write the generated index to standard output.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        content = render_index(load_routing(args.routing))
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    output = args.output.expanduser().resolve()
    if args.stdout:
        print(content, end="")
        return 0
    if args.check:
        try:
            current = output.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current == content:
            print(f"index is current: {output}")
            return 0
        print(f"index requires refresh: {output}", file=sys.stderr)
        return 1

    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
    except OSError as error:
        print(f"error: cannot write generated index: {error}", file=sys.stderr)
        return 2
    print(f"generated index: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
